version: "3.4"

services:
  app:
    build:
      context: ./_docker
      dockerfile: app.Dockerfile
      args:
        UID: 1000
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
